# Book settings
title: MRI classification using Clinica
author: The Aramis Team
logo: 'images/logo1.png'

launch_buttons:
  colab_url: "https://colab.research.google.com/github/aramis-lab/Notebooks-AD-DL"
   # jupyterhub_url: "localhost:8080"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  
######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
