# Book settings
title: MRI classification using Clinica
author: The Aramis Team
logo: 'images/logo1.png'

launch_buttons:
  jupyterhub_url: "localhost:8080"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
    
